project:
  type: website
  execute-dir: project

website:
  title: Middle Stump Metrics
  navbar:
    background: primary
    tools:
      - icon: github
        href: https://github.com/bairdj/middle-stump-metrics
  sidebar:
    style: docked
    contents: analyses


format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    code-fold: true

execute:
  warning: false