---
title: Batting collapses
author: James Baird
---

```{r}
#| label: setup
#| include: false

library(here)
library(dplyr)
library(gt)
library(tidyr)
source(here("R", "model.R"))
source(here("R", "util.R"))

db <- Model$new()
```

Batting collapses are identified by comparing the score at each fall of
wicket to the score at previous falls of wicket. This uses a variable
length window over all wickets, therefore, each wicket may be counted
as part of different collapses.

```{r}
wickets <- db$table("Wicket") |>
  count(MatchId, InningsNumber, Over, Ball, name = "wickets")

innings_progression <-
  db$table("Delivery") |>
  left_join(wickets, by = c("MatchId", "InningsNumber", "Over", "Ball")) |>
  mutate(wickets = coalesce(wickets, 0)) |>
  group_by(MatchId, InningsNumber) |>
  dbplyr::window_order(Over, Ball) |>
  mutate(
    ball = row_number(),
    cum_runs = cumsum(TotalRuns),
    cum_wickets = cumsum(wickets)
  ) |>
  collapse() |>
  group_by(cum_wickets, .add = TRUE) |>
  summarise(
    ball = min(ball),
    cum_runs = min(cum_runs),
    .groups = "drop"
  ) |>
  collect()

# Create expressions for all possible collapses
collapse_range <- 2:10
names(collapse_range) <- paste0("collapse_", collapse_range)

lag_exprs <- purrr::map(
  collapse_range,
  ~ expr(cum_runs - lag(cum_runs, !!.x - 1))
)

match_detail <-
  db$table("Match") |>
  mutate(match_link = !!create_match_link_expr("Scorecard", MatchId))

innings_progression |>
  filter(cum_wickets > 0) |>
  group_by(MatchId, InningsNumber) |>
  arrange(cum_wickets) |>
  mutate(!!!lag_exprs) |>
  ungroup() |>
  pivot_longer(
    cols = starts_with("collapse_"),
    names_to = "collapse_wickets",
    names_prefix = "collapse_",
    names_transform = list(collapse_wickets = as.integer),
    values_to = "runs",
    values_drop_na = TRUE
  ) |>
  filter(collapse_wickets >= 5) |>
  group_by(collapse_wickets) |>
  slice_min(runs, n = 10, with_ties = TRUE) |>
  inner_join(
    collect(db$table("Innings")),
    by = c("MatchId", "InningsNumber")
  ) |>
  inner_join(collect(match_detail), by = "MatchId") |>
  select(
    StartDate,
    Venue,
    collapse_wickets,
    BattingTeam,
    BowlingTeam,
    Runs = runs,
    match_link
  ) |>
  mutate(collapse_wickets = paste0(collapse_wickets, " wickets")) |>
  gt() |>
  cols_label(
    StartDate = "Date",
    BattingTeam = "Batting team",
    BowlingTeam = "Bowling team",
    match_link = "Scorecard"
  ) |>
  fmt_date(columns = "StartDate", date_style = 7) |>
  fmt_markdown(match_link) |>
  tab_header(
    title = "Batting collapses",
    subtitle = "Lowest scores after losing a given number of wickets"
  ) |>
  tab_style(
    cell_text(weight = "bold", size = "large"),
    locations = cells_row_groups()
  )
```

