name: build-site
on:
  push:
    branches: [ actions ]
jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parse-cricsheet
        uses: actions/checkout@v3
        with:
          repository: bairdj/parse-cricsheet
      - name: Download Cricsheet data
        run: |
          wget https://cricsheet.org/downloads/tests_male_json.zip
          wget https://cricsheet.org/register/people.csv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Run
        run: dotnet run --register people.csv tests_male_json.zip output.db
      - name: Upload database
        uses: actions/upload-artifact@v3
        with:
          name: output.db
          path: output.db
      