name: build-site
on:
  push:
    branches: [ actions ]
jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parse-cricsheet
        uses: actions/checkout@v3
        with:
          repository: bairdj/parse-cricsheet
      - name: Download Cricsheet data
        run: |
          wget https://cricsheet.org/downloads/tests_male_json.zip
          wget https://cricsheet.org/register/people.csv
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: dotnet restore
      - name: Run
        run: dotnet run --register people.csv tests_male_json.zip output.db
      - name: Upload database
        uses: actions/upload-artifact@v3
        with:
          name: output.db
          path: output.db
  build-site:
    needs: load-data
    env:
      DB_LOCATION: output.db
    steps:
      - uses: actions/checkout@v3
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Configure renv
        uses: r-lib/actions/setup-renv@v2
      - name: Load data artifact
        uses: actions/download-artifact@v2
        with:
          name: output.db
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site
  deploy:
    needs: build-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        